packages:
  - apps/*
  - example
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@astrojs/mdx": latest
  "@tailwindcss/vite": latest
  "@types/node": ^24
  astro: latest
  gunshi: latest
  jiti: ^2.7.0
  tailwindcss: latest
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  esbuild: true
  sharp: true
