export {
  SUPPORTED_DECK_EXTENSIONS,
  VIRTUAL_SLIDA_DECK_ID,
  VIRTUAL_SLIDA_DECK_PREFIX,
  VIRTUAL_SLIDA_ROUTE_PREFIX,
  VIRTUAL_SLIDA_THEME_LAYOUTS_ID,
  collectStaticAstroCodeBlocksForTests,
  countAstroDeckPages,
  countMdxDeckPages,
  createDeckRegistry,
  createGeneratedPageComponentSource,
  createRuntimePageSource,
  createSlidaVitePlugins,
  createSlidaVitePluginsForRegistry,
  createSourceIndexConverter,
  createThemeLayoutDiscoveryCache,
  discoverThemeLayouts,
  extractAstroSlotNames,
  inferDeckFormat,
  normalizeIdPath,
  normalizePath,
  normalizeSlidaBasePath,
  remarkSlidaMdxPages,
  resolveDeckFile,
  resolveDeckFilesFromGlob,
  resolveDeckRegistry,
  splitMdxChildrenIntoPages,
  stripMdxFrontmatter,
  toViteFsImportPath,
  transformAstroDeckSource,
  transformAstroDeckSourceWithCodeHighlighting,
  transformCompiledAstroDeckSource,
  uniqueStrings,
  validateAstroDeckSource,
} from "@slida/core";
export {
  defineConfig,
  findSlidaConfigFiles,
  loadSlidaConfig,
  SLIDA_CONFIG_FILES,
} from "./config.ts";
export {
  buildDeck,
  createAstroInlineConfig,
  createSlidaAstroConfig,
  DEFAULT_EXPORT_SEARCH_PARAM,
  DEFAULT_EXPORT_SEARCH_VALUE,
  exportDeck,
  normalizeBuildOutDir,
  normalizeExportOutFile,
  startDevServer,
} from "./astro.ts";
export {
  BUILTIN_SLIDA_THEME_PACKAGES,
  BUILTIN_SLIDA_THEMES,
  DEFAULT_SLIDA_THEME,
  resolveSlidaThemeLayouts,
} from "./theme.ts";
export {
  normalizeBuildFormat,
  normalizeBuildValues,
  normalizeLogLevel,
  normalizeOpenValues,
  runSlida,
} from "./commands.ts";
export {
  pathExists,
  prepareRuntime,
  resolveProjectRoot,
  resolveRuntimeSourceDir,
} from "./runtime.ts";
export type {
  AstroAttribute,
  AstroIdentifier,
  AstroImportDeclaration,
  AstroNode,
  AstroRoot,
  RawAstroCodeHighlightOptions,
  RuntimePageSourceOptions,
  SlidaDeckFormat,
  SlidaDeckRegistry,
  SlidaMdxPagesOptions,
  SlidaResolvedDeck,
  SlidaResolvedDeckRoute,
  SlidaResolvedTheme,
  SlidaResolvedThemeLayout,
  SlidaRouteId,
  SlidaRuntimePaths,
  SlidaVitePluginOptions,
} from "@slida/core";
export type {
  SlidaAstroConfig,
  SlidaBaseOptions,
  SlidaBuildCommandOptions,
  SlidaBuildOptions,
  SlidaConfig,
  SlidaDevOptions,
  SlidaDevResult,
  SlidaExportOptions,
  SlidaExportResult,
  SlidaLoadedConfig,
  SlidaLogLevel,
  SlidaOutputFormat,
  SlidaResolvedConfig,
} from "./types.ts";
